# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ben/Desktop/UIUC_Research/FBG_SiMul/Python_Version/GUI/PlotWindow_OSA.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(682, 724)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("DESIGN_Resource/plot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_OSA_Plot = QtWidgets.QGridLayout()
        self.gridLayout_OSA_Plot.setObjectName("gridLayout_OSA_Plot")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_OSA_Plot.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_OSA_Plot, 0, 0, 1, 1)
        self.gridLayoutControl_OSA = QtWidgets.QGridLayout()
        self.gridLayoutControl_OSA.setObjectName("gridLayoutControl_OSA")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.spinBox_XlimMin = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_XlimMin.setFont(font)
        self.spinBox_XlimMin.setMinimum(0)
        self.spinBox_XlimMin.setMaximum(5000)
        self.spinBox_XlimMin.setSingleStep(10)
        self.spinBox_XlimMin.setProperty("value", 1500)
        self.spinBox_XlimMin.setObjectName("spinBox_XlimMin")
        self.gridLayout_3.addWidget(self.spinBox_XlimMin, 1, 0, 1, 1)
        self.doubleSpinBox_XlimMax = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_XlimMax.setFont(font)
        self.doubleSpinBox_XlimMax.setDecimals(0)
        self.doubleSpinBox_XlimMax.setMinimum(0.0)
        self.doubleSpinBox_XlimMax.setMaximum(5000.0)
        self.doubleSpinBox_XlimMax.setSingleStep(10.0)
        self.doubleSpinBox_XlimMax.setProperty("value", 1600.0)
        self.doubleSpinBox_XlimMax.setObjectName("doubleSpinBox_XlimMax")
        self.gridLayout_3.addWidget(self.doubleSpinBox_XlimMax, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 3, 1, 1, 1)
        self.doubleSpinBox_YlimMax = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_YlimMax.setFont(font)
        self.doubleSpinBox_YlimMax.setDecimals(2)
        self.doubleSpinBox_YlimMax.setMinimum(0.0)
        self.doubleSpinBox_YlimMax.setMaximum(2.0)
        self.doubleSpinBox_YlimMax.setSingleStep(0.1)
        self.doubleSpinBox_YlimMax.setProperty("value", 1.0)
        self.doubleSpinBox_YlimMax.setObjectName("doubleSpinBox_YlimMax")
        self.gridLayout_3.addWidget(self.doubleSpinBox_YlimMax, 3, 2, 1, 1)
        self.spinBox_YlimMin = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_YlimMin.setFont(font)
        self.spinBox_YlimMin.setMinimum(0)
        self.spinBox_YlimMin.setMaximum(2)
        self.spinBox_YlimMin.setSingleStep(1)
        self.spinBox_YlimMin.setProperty("value", 0)
        self.spinBox_YlimMin.setObjectName("spinBox_YlimMin")
        self.gridLayout_3.addWidget(self.spinBox_YlimMin, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 3)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 3, 0, 2, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 2)
        self.comboBox_LineColorUndeformed = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_LineColorUndeformed.setFont(font)
        self.comboBox_LineColorUndeformed.setObjectName("comboBox_LineColorUndeformed")
        self.comboBox_LineColorUndeformed.addItem("")
        self.comboBox_LineColorUndeformed.addItem("")
        self.comboBox_LineColorUndeformed.addItem("")
        self.comboBox_LineColorUndeformed.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_LineColorUndeformed, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 1)
        self.comboBox_LineColorSimulated = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_LineColorSimulated.setFont(font)
        self.comboBox_LineColorSimulated.setObjectName("comboBox_LineColorSimulated")
        self.comboBox_LineColorSimulated.addItem("")
        self.comboBox_LineColorSimulated.addItem("")
        self.comboBox_LineColorSimulated.addItem("")
        self.comboBox_LineColorSimulated.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_LineColorSimulated, 3, 1, 2, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.doubleSpinBox_LineWidth = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_LineWidth.setFont(font)
        self.doubleSpinBox_LineWidth.setDecimals(2)
        self.doubleSpinBox_LineWidth.setMinimum(0.1)
        self.doubleSpinBox_LineWidth.setMaximum(10.0)
        self.doubleSpinBox_LineWidth.setSingleStep(0.1)
        self.doubleSpinBox_LineWidth.setProperty("value", 0.5)
        self.doubleSpinBox_LineWidth.setObjectName("doubleSpinBox_LineWidth")
        self.gridLayout_4.addWidget(self.doubleSpinBox_LineWidth, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.groupBox_2)
        self.checkBox_legend = QtWidgets.QCheckBox(Form)
        self.checkBox_legend.setChecked(False)
        self.checkBox_legend.setObjectName("checkBox_legend")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.checkBox_legend)
        spacerItem1 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.pushButton_SavePicture = QtWidgets.QPushButton(Form)
        self.pushButton_SavePicture.setObjectName("pushButton_SavePicture")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.pushButton_SavePicture)
        self.checkBox_Grid = QtWidgets.QCheckBox(Form)
        self.checkBox_Grid.setObjectName("checkBox_Grid")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.checkBox_Grid)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.textEdit_FBGoutput = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_FBGoutput.setMinimumSize(QtCore.QSize(170, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_FBGoutput.setFont(font)
        self.textEdit_FBGoutput.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_FBGoutput.setObjectName("textEdit_FBGoutput")
        self.gridLayout_6.addWidget(self.textEdit_FBGoutput, 0, 0, 1, 1)
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.groupBox_3)
        self.gridLayoutControl_OSA.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayoutControl_OSA, 0, 1, 1, 1)
        self.actionSavePicture = QtWidgets.QAction(Form)
        self.actionSavePicture.setObjectName("actionSavePicture")

        self.retranslateUi(Form)
        self.pushButton_SavePicture.clicked.connect(self.actionSavePicture.trigger)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Plot FBG Spectrum"))
        self.groupBox.setTitle(_translate("Form", "Axis Control"))
        self.label_3.setText(_translate("Form", "to"))
        self.label.setText(_translate("Form", "to"))
        self.label_4.setText(_translate("Form", "Reflectivity (R)"))
        self.label_2.setText(_translate("Form", "Wavelength (nm)"))
        self.groupBox_2.setTitle(_translate("Form", "Line Properties"))
        self.label_8.setText(_translate("Form", "Simulated Spectrum"))
        self.label_6.setText(_translate("Form", "Line Color:"))
        self.comboBox_LineColorUndeformed.setItemText(0, _translate("Form", "grey"))
        self.comboBox_LineColorUndeformed.setItemText(1, _translate("Form", "blue"))
        self.comboBox_LineColorUndeformed.setItemText(2, _translate("Form", "red"))
        self.comboBox_LineColorUndeformed.setItemText(3, _translate("Form", "black"))
        self.label_7.setText(_translate("Form", "Undeformed Spectrum "))
        self.comboBox_LineColorSimulated.setItemText(0, _translate("Form", "blue"))
        self.comboBox_LineColorSimulated.setItemText(1, _translate("Form", "red"))
        self.comboBox_LineColorSimulated.setItemText(2, _translate("Form", "black"))
        self.comboBox_LineColorSimulated.setItemText(3, _translate("Form", "grey"))
        self.label_5.setText(_translate("Form", "Line Width:"))
        self.checkBox_legend.setText(_translate("Form", "Legend"))
        self.pushButton_SavePicture.setText(_translate("Form", "Save Picture"))
        self.checkBox_Grid.setText(_translate("Form", "Grid"))
        self.groupBox_3.setTitle(_translate("Form", "FBG Output "))
        self.textEdit_FBGoutput.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.actionSavePicture.setText(_translate("Form", "SavePicture"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

