# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ben/Desktop/UIUC_Research/FBG_SiMul/Python_Version/GUI/PlotWindow_TR.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(832, 724)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("DESIGN_Resource/plot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_TR_Plot = QtWidgets.QGridLayout()
        self.gridLayout_TR_Plot.setObjectName("gridLayout_TR_Plot")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_TR_Plot.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_TR_Plot, 0, 0, 1, 1)
        self.gridLayoutControl_OSA = QtWidgets.QGridLayout()
        self.gridLayoutControl_OSA.setObjectName("gridLayoutControl_OSA")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 1, 1, 1)
        self.doubleSpinBox_MaxIncrement = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_MaxIncrement.setFont(font)
        self.doubleSpinBox_MaxIncrement.setDecimals(0)
        self.doubleSpinBox_MaxIncrement.setMinimum(0.0)
        self.doubleSpinBox_MaxIncrement.setMaximum(100000.0)
        self.doubleSpinBox_MaxIncrement.setSingleStep(1.0)
        self.doubleSpinBox_MaxIncrement.setProperty("value", 1.0)
        self.doubleSpinBox_MaxIncrement.setObjectName("doubleSpinBox_MaxIncrement")
        self.gridLayout_3.addWidget(self.doubleSpinBox_MaxIncrement, 1, 2, 1, 1)
        self.spinBox_MinIncrement = QtWidgets.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_MinIncrement.setFont(font)
        self.spinBox_MinIncrement.setMinimum(0)
        self.spinBox_MinIncrement.setMaximum(10000)
        self.spinBox_MinIncrement.setSingleStep(1)
        self.spinBox_MinIncrement.setProperty("value", 0)
        self.spinBox_MinIncrement.setObjectName("spinBox_MinIncrement")
        self.gridLayout_3.addWidget(self.spinBox_MinIncrement, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 5, 1, 1, 1)
        self.spinBox_WSMin = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_WSMin.setFont(font)
        self.spinBox_WSMin.setDecimals(3)
        self.spinBox_WSMin.setMinimum(-99.0)
        self.spinBox_WSMin.setSingleStep(0.1)
        self.spinBox_WSMin.setObjectName("spinBox_WSMin")
        self.gridLayout_3.addWidget(self.spinBox_WSMin, 3, 0, 1, 1)
        self.spinBox_WSMax = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_WSMax.setFont(font)
        self.spinBox_WSMax.setDecimals(3)
        self.spinBox_WSMax.setMinimum(-99.0)
        self.spinBox_WSMax.setSingleStep(0.1)
        self.spinBox_WSMax.setObjectName("spinBox_WSMax")
        self.gridLayout_3.addWidget(self.spinBox_WSMax, 3, 2, 1, 1)
        self.spinBox_WDMin = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_WDMin.setFont(font)
        self.spinBox_WDMin.setDecimals(3)
        self.spinBox_WDMin.setMinimum(-99.0)
        self.spinBox_WDMin.setSingleStep(0.1)
        self.spinBox_WDMin.setObjectName("spinBox_WDMin")
        self.gridLayout_3.addWidget(self.spinBox_WDMin, 5, 0, 1, 1)
        self.spinBox_WDMax = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_WDMax.setFont(font)
        self.spinBox_WDMax.setDecimals(3)
        self.spinBox_WDMax.setMinimum(-99.0)
        self.spinBox_WDMax.setSingleStep(0.1)
        self.spinBox_WDMax.setObjectName("spinBox_WDMax")
        self.gridLayout_3.addWidget(self.spinBox_WDMax, 5, 2, 1, 1)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.doubleSpinBox_LineWidth = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_LineWidth.setFont(font)
        self.doubleSpinBox_LineWidth.setDecimals(2)
        self.doubleSpinBox_LineWidth.setMinimum(0.1)
        self.doubleSpinBox_LineWidth.setMaximum(10.0)
        self.doubleSpinBox_LineWidth.setSingleStep(0.1)
        self.doubleSpinBox_LineWidth.setProperty("value", 0.5)
        self.doubleSpinBox_LineWidth.setObjectName("doubleSpinBox_LineWidth")
        self.gridLayout_4.addWidget(self.doubleSpinBox_LineWidth, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.groupBox_2)
        self.checkBox_legend = QtWidgets.QCheckBox(Form)
        self.checkBox_legend.setChecked(False)
        self.checkBox_legend.setObjectName("checkBox_legend")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.checkBox_legend)
        spacerItem1 = QtWidgets.QSpacerItem(20, 350, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.pushButton_SavePicture = QtWidgets.QPushButton(Form)
        self.pushButton_SavePicture.setObjectName("pushButton_SavePicture")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.pushButton_SavePicture)
        self.checkBox_Grid = QtWidgets.QCheckBox(Form)
        self.checkBox_Grid.setObjectName("checkBox_Grid")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.checkBox_Grid)
        self.gridLayoutControl_OSA.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayoutControl_OSA, 0, 1, 1, 1)
        self.actionSavePicture = QtWidgets.QAction(Form)
        self.actionSavePicture.setObjectName("actionSavePicture")

        self.retranslateUi(Form)
        self.pushButton_SavePicture.clicked.connect(self.actionSavePicture.trigger)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Plot FBG Spectrum"))
        self.groupBox.setTitle(_translate("Form", "Axis Control"))
        self.label_2.setText(_translate("Form", "Increments"))
        self.label.setText(_translate("Form", "to"))
        self.label_4.setText(_translate("Form", "Wavelength Shift (nm)"))
        self.label_3.setText(_translate("Form", "to"))
        self.label_6.setText(_translate("Form", "Peak width variation (nm)"))
        self.label_7.setText(_translate("Form", "to"))
        self.groupBox_2.setTitle(_translate("Form", "Line Properties"))
        self.label_5.setText(_translate("Form", "Line Width:"))
        self.checkBox_legend.setText(_translate("Form", "Legend"))
        self.pushButton_SavePicture.setText(_translate("Form", "Save Picture"))
        self.checkBox_Grid.setText(_translate("Form", "Grid"))
        self.actionSavePicture.setText(_translate("Form", "SavePicture"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

