# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ben/OneDrive - University of St. Thomas/UIUC_Research/scripts/FBG-SimPlus/python/GUI/MyPlotMainWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 860)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../.designer/backup/DESIGN_Resource/plot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayoutPlot = QtWidgets.QGridLayout()
        self.gridLayoutPlot.setObjectName("gridLayoutPlot")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.gridLayoutPlot.addWidget(self.label, 0, 0, 1, 1)
        self.MessageBoard = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MessageBoard.sizePolicy().hasHeightForWidth())
        self.MessageBoard.setSizePolicy(sizePolicy)
        self.MessageBoard.setMinimumSize(QtCore.QSize(250, 500))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(247, 245, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 234, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 245, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 234, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 234, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        self.MessageBoard.setPalette(palette)
        self.MessageBoard.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.MessageBoard.setCenterOnScroll(False)
        self.MessageBoard.setObjectName("MessageBoard")
        self.gridLayoutPlot.addWidget(self.MessageBoard, 1, 0, 1, 1)
        self.pushButton_ClearMessageBoard = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ClearMessageBoard.sizePolicy().hasHeightForWidth())
        self.pushButton_ClearMessageBoard.setSizePolicy(sizePolicy)
        self.pushButton_ClearMessageBoard.setObjectName("pushButton_ClearMessageBoard")
        self.gridLayoutPlot.addWidget(self.pushButton_ClearMessageBoard, 2, 0, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.gridLayoutPlot.addWidget(self.label_64, 3, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayoutPlot)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_23.setObjectName("gridLayout_23")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_23.addItem(spacerItem, 4, 2, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_12.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_12.sizePolicy().hasHeightForWidth())
        self.groupBox_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_24 = QtWidgets.QLabel(self.groupBox_12)
        self.label_24.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_12)
        self.label_22.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_12)
        self.label_23.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 2, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_12)
        self.label_29.setEnabled(True)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 3, 0, 1, 2)
        self.lineEdit_MaxBandWidth = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_MaxBandWidth.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_MaxBandWidth.setFont(font)
        self.lineEdit_MaxBandWidth.setObjectName("lineEdit_MaxBandWidth")
        self.gridLayout_2.addWidget(self.lineEdit_MaxBandWidth, 2, 2, 1, 1)
        self.lineEdit_AmbientTemperature = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_AmbientTemperature.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_AmbientTemperature.setFont(font)
        self.lineEdit_AmbientTemperature.setObjectName("lineEdit_AmbientTemperature")
        self.gridLayout_2.addWidget(self.lineEdit_AmbientTemperature, 3, 2, 1, 1)
        self.lineEdit_MinBandWidth = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_MinBandWidth.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_MinBandWidth.setFont(font)
        self.lineEdit_MinBandWidth.setObjectName("lineEdit_MinBandWidth")
        self.gridLayout_2.addWidget(self.lineEdit_MinBandWidth, 1, 2, 1, 1)
        self.lineEdit_SimulationResolution = QtWidgets.QLineEdit(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_SimulationResolution.sizePolicy().hasHeightForWidth())
        self.lineEdit_SimulationResolution.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_SimulationResolution.setFont(font)
        self.lineEdit_SimulationResolution.setObjectName("lineEdit_SimulationResolution")
        self.gridLayout_2.addWidget(self.lineEdit_SimulationResolution, 0, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMouseTracking(True)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 0, 0, 1, 2)
        self.gridLayout_33.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.checkBox_AdvancedModeSelectionOSA = QtWidgets.QCheckBox(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_AdvancedModeSelectionOSA.sizePolicy().hasHeightForWidth())
        self.checkBox_AdvancedModeSelectionOSA.setSizePolicy(sizePolicy)
        self.checkBox_AdvancedModeSelectionOSA.setObjectName("checkBox_AdvancedModeSelectionOSA")
        self.gridLayout_33.addWidget(self.checkBox_AdvancedModeSelectionOSA, 2, 1, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.lineEdit_DirectionalRefractiveP11 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_DirectionalRefractiveP11.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_DirectionalRefractiveP11.setFont(font)
        self.lineEdit_DirectionalRefractiveP11.setObjectName("lineEdit_DirectionalRefractiveP11")
        self.gridLayout_22.addWidget(self.lineEdit_DirectionalRefractiveP11, 3, 2, 1, 2)
        self.lineEdit_PoissionsCoefficient = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_PoissionsCoefficient.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_PoissionsCoefficient.setFont(font)
        self.lineEdit_PoissionsCoefficient.setObjectName("lineEdit_PoissionsCoefficient")
        self.gridLayout_22.addWidget(self.lineEdit_PoissionsCoefficient, 6, 1, 1, 3)
        self.label_15 = QtWidgets.QLabel(self.groupBox_12)
        self.label_15.setEnabled(False)
        self.label_15.setMouseTracking(True)
        self.label_15.setObjectName("label_15")
        self.gridLayout_22.addWidget(self.label_15, 4, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_12)
        self.label_16.setEnabled(False)
        self.label_16.setObjectName("label_16")
        self.gridLayout_22.addWidget(self.label_16, 5, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_12)
        self.label_14.setEnabled(False)
        self.label_14.setMouseTracking(True)
        self.label_14.setObjectName("label_14")
        self.gridLayout_22.addWidget(self.label_14, 3, 1, 1, 1)
        self.lineEdit_FringeVisibility = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_FringeVisibility.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_FringeVisibility.setFont(font)
        self.lineEdit_FringeVisibility.setObjectName("lineEdit_FringeVisibility")
        self.gridLayout_22.addWidget(self.lineEdit_FringeVisibility, 2, 1, 1, 3)
        self.lineEdit_YoungsModule = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_YoungsModule.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_YoungsModule.setFont(font)
        self.lineEdit_YoungsModule.setObjectName("lineEdit_YoungsModule")
        self.gridLayout_22.addWidget(self.lineEdit_YoungsModule, 5, 1, 1, 3)
        self.lineEdit_DirectionalRefractiveP12 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_DirectionalRefractiveP12.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_DirectionalRefractiveP12.setFont(font)
        self.lineEdit_DirectionalRefractiveP12.setObjectName("lineEdit_DirectionalRefractiveP12")
        self.gridLayout_22.addWidget(self.lineEdit_DirectionalRefractiveP12, 4, 2, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.groupBox_12)
        self.label_13.setEnabled(False)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout_22.addWidget(self.label_13, 3, 0, 2, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_12)
        self.label_17.setEnabled(False)
        self.label_17.setObjectName("label_17")
        self.gridLayout_22.addWidget(self.label_17, 6, 0, 1, 1)
        self.lineEdit_MeanChangeRefractiveIndex = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_MeanChangeRefractiveIndex.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_MeanChangeRefractiveIndex.setFont(font)
        self.lineEdit_MeanChangeRefractiveIndex.setObjectName("lineEdit_MeanChangeRefractiveIndex")
        self.gridLayout_22.addWidget(self.lineEdit_MeanChangeRefractiveIndex, 1, 1, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.groupBox_12)
        self.label_9.setEnabled(False)
        self.label_9.setObjectName("label_9")
        self.gridLayout_22.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_12)
        self.label_10.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.gridLayout_22.addWidget(self.label_10, 1, 0, 1, 1)
        self.lineEdit_InitialRefractiveIndex = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_InitialRefractiveIndex.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_InitialRefractiveIndex.setFont(font)
        self.lineEdit_InitialRefractiveIndex.setObjectName("lineEdit_InitialRefractiveIndex")
        self.gridLayout_22.addWidget(self.lineEdit_InitialRefractiveIndex, 0, 1, 1, 3)
        self.label_12 = QtWidgets.QLabel(self.groupBox_12)
        self.label_12.setEnabled(False)
        self.label_12.setObjectName("label_12")
        self.gridLayout_22.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox_12)
        self.label_48.setEnabled(False)
        self.label_48.setObjectName("label_48")
        self.gridLayout_22.addWidget(self.label_48, 7, 0, 1, 1)
        self.lineEdit_ThermoOptic = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_ThermoOptic.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_ThermoOptic.setFont(font)
        self.lineEdit_ThermoOptic.setObjectName("lineEdit_ThermoOptic")
        self.gridLayout_22.addWidget(self.lineEdit_ThermoOptic, 7, 1, 1, 3)
        self.gridLayout_33.addLayout(self.gridLayout_22, 3, 1, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_12, 2, 0, 1, 2)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setObjectName("gridLayout_31")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_31.addItem(spacerItem1, 1, 0, 2, 1)
        self.radioButton_TypeUniform = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_TypeUniform.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_TypeUniform.sizePolicy().hasHeightForWidth())
        self.radioButton_TypeUniform.setSizePolicy(sizePolicy)
        self.radioButton_TypeUniform.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_TypeUniform.setFont(font)
        self.radioButton_TypeUniform.setObjectName("radioButton_TypeUniform")
        self.gridLayout_31.addWidget(self.radioButton_TypeUniform, 1, 1, 1, 1)
        self.radioButton_TypeNonUniform = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_TypeNonUniform.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_TypeNonUniform.setFont(font)
        self.radioButton_TypeNonUniform.setChecked(True)
        self.radioButton_TypeNonUniform.setObjectName("radioButton_TypeNonUniform")
        self.gridLayout_31.addWidget(self.radioButton_TypeNonUniform, 2, 1, 1, 1)
        self.checkBox_TypeStrain = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_TypeStrain.setObjectName("checkBox_TypeStrain")
        self.gridLayout_31.addWidget(self.checkBox_TypeStrain, 0, 0, 1, 2)
        self.checkBox_TypeTransverseStress = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_TypeTransverseStress.setObjectName("checkBox_TypeTransverseStress")
        self.gridLayout_31.addWidget(self.checkBox_TypeTransverseStress, 3, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_31.addItem(spacerItem2, 4, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_31.addWidget(self.label_2, 5, 0, 1, 2)
        self.lineEdit_EmulateTemperature = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_EmulateTemperature.setEnabled(False)
        self.lineEdit_EmulateTemperature.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_EmulateTemperature.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_EmulateTemperature.setFont(font)
        self.lineEdit_EmulateTemperature.setObjectName("lineEdit_EmulateTemperature")
        self.gridLayout_31.addWidget(self.lineEdit_EmulateTemperature, 6, 1, 1, 1, QtCore.Qt.AlignRight)
        self.checkBox_TypeEmulateTemperature = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_TypeEmulateTemperature.setEnabled(True)
        self.checkBox_TypeEmulateTemperature.setObjectName("checkBox_TypeEmulateTemperature")
        self.gridLayout_31.addWidget(self.checkBox_TypeEmulateTemperature, 6, 0, 1, 1)
        self.lineEdit_HostThermalExpansion = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_HostThermalExpansion.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_HostThermalExpansion.setFont(font)
        self.lineEdit_HostThermalExpansion.setObjectName("lineEdit_HostThermalExpansion")
        self.gridLayout_31.addWidget(self.lineEdit_HostThermalExpansion, 7, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.groupBox_9)
        self.label_49.setEnabled(False)
        self.label_49.setWordWrap(True)
        self.label_49.setObjectName("label_49")
        self.gridLayout_31.addWidget(self.label_49, 7, 0, 1, 1)
        self.gridLayout_32.addLayout(self.gridLayout_31, 0, 1, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_9, 0, 2, 2, 2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.pushButton_LoadFolder = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_LoadFolder.setObjectName("pushButton_LoadFolder")
        self.gridLayout_19.addWidget(self.pushButton_LoadFolder, 1, 1, 1, 1)
        self.pushButton_RemoveFileStressStrain = QtWidgets.QPushButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_RemoveFileStressStrain.setFont(font)
        self.pushButton_RemoveFileStressStrain.setObjectName("pushButton_RemoveFileStressStrain")
        self.gridLayout_19.addWidget(self.pushButton_RemoveFileStressStrain, 2, 1, 1, 1)
        self.spinBox_SkipRow = QtWidgets.QSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_SkipRow.sizePolicy().hasHeightForWidth())
        self.spinBox_SkipRow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_SkipRow.setFont(font)
        self.spinBox_SkipRow.setProperty("value", 3)
        self.spinBox_SkipRow.setObjectName("spinBox_SkipRow")
        self.gridLayout_19.addWidget(self.spinBox_SkipRow, 4, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_19.addWidget(self.label_30, 4, 0, 1, 1)
        self.listWidget_stressStrainFiles = QtWidgets.QListWidget(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.listWidget_stressStrainFiles.setFont(font)
        self.listWidget_stressStrainFiles.setObjectName("listWidget_stressStrainFiles")
        self.gridLayout_19.addWidget(self.listWidget_stressStrainFiles, 1, 0, 3, 1)
        self.pushButton_HelpFileFormatOSA = QtWidgets.QPushButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_HelpFileFormatOSA.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../.designer/backup/DESIGN_Resource/Help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_HelpFileFormatOSA.setIcon(icon1)
        self.pushButton_HelpFileFormatOSA.setObjectName("pushButton_HelpFileFormatOSA")
        self.gridLayout_19.addWidget(self.pushButton_HelpFileFormatOSA, 3, 1, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_19, 0, 1, 1, 1)
        self.groupBox_20 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_54 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_54.setObjectName("gridLayout_54")
        self.gridLayout_48 = QtWidgets.QGridLayout()
        self.gridLayout_48.setObjectName("gridLayout_48")
        self.radioButton_InputUnitsSIM = QtWidgets.QRadioButton(self.groupBox_20)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_InputUnitsSIM.setFont(font)
        self.radioButton_InputUnitsSIM.setChecked(True)
        self.radioButton_InputUnitsSIM.setObjectName("radioButton_InputUnitsSIM")
        self.gridLayout_48.addWidget(self.radioButton_InputUnitsSIM, 0, 0, 1, 1)
        self.gridLayout_54.addLayout(self.gridLayout_48, 0, 0, 1, 1)
        self.radioButton_InputUnitsSIMM = QtWidgets.QRadioButton(self.groupBox_20)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_InputUnitsSIMM.setFont(font)
        self.radioButton_InputUnitsSIMM.setObjectName("radioButton_InputUnitsSIMM")
        self.gridLayout_54.addWidget(self.radioButton_InputUnitsSIMM, 0, 1, 1, 1)
        self.gridLayout_20.addWidget(self.groupBox_20, 1, 1, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_6, 0, 0, 2, 2)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.checkBox_UndeformedSignal = QtWidgets.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_UndeformedSignal.setFont(font)
        self.checkBox_UndeformedSignal.setObjectName("checkBox_UndeformedSignal")
        self.gridLayout_26.addWidget(self.checkBox_UndeformedSignal, 0, 0, 1, 2)
        self.pushButton_PlotOSA = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_PlotOSA.setObjectName("pushButton_PlotOSA")
        self.gridLayout_26.addWidget(self.pushButton_PlotOSA, 0, 4, 1, 1)
        self.pushButton_OSAGenerate = QtWidgets.QPushButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.pushButton_OSAGenerate.setFont(font)
        self.pushButton_OSAGenerate.setObjectName("pushButton_OSAGenerate")
        self.gridLayout_26.addWidget(self.pushButton_OSAGenerate, 0, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_8)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_26.addWidget(self.progressBar, 0, 3, 1, 1)
        self.pushButton_SaveasFileOSA = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_SaveasFileOSA.setObjectName("pushButton_SaveasFileOSA")
        self.gridLayout_26.addWidget(self.pushButton_SaveasFileOSA, 0, 5, 1, 1)
        self.gridLayout_37.addLayout(self.gridLayout_26, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_8, 3, 0, 1, 4)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.pushButton_ClearFBGPosition = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ClearFBGPosition.sizePolicy().hasHeightForWidth())
        self.pushButton_ClearFBGPosition.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_ClearFBGPosition.setFont(font)
        self.pushButton_ClearFBGPosition.setObjectName("pushButton_ClearFBGPosition")
        self.gridLayout_29.addWidget(self.pushButton_ClearFBGPosition, 4, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_29.addWidget(self.label_19, 0, 2, 1, 1)
        self.lineEdit_FBGlength = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_FBGlength.sizePolicy().hasHeightForWidth())
        self.lineEdit_FBGlength.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_FBGlength.setFont(font)
        self.lineEdit_FBGlength.setObjectName("lineEdit_FBGlength")
        self.gridLayout_29.addWidget(self.lineEdit_FBGlength, 0, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_29.addWidget(self.label_18, 0, 0, 1, 1)
        self.pushButton_ClearFBGOriginalWavelength = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ClearFBGOriginalWavelength.sizePolicy().hasHeightForWidth())
        self.pushButton_ClearFBGOriginalWavelength.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_ClearFBGOriginalWavelength.setFont(font)
        self.pushButton_ClearFBGOriginalWavelength.setObjectName("pushButton_ClearFBGOriginalWavelength")
        self.gridLayout_29.addWidget(self.pushButton_ClearFBGOriginalWavelength, 11, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_29.addWidget(self.label_21, 7, 0, 1, 3)
        self.spinBox_NumberFBG = QtWidgets.QSpinBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_NumberFBG.setFont(font)
        self.spinBox_NumberFBG.setMinimum(1)
        self.spinBox_NumberFBG.setObjectName("spinBox_NumberFBG")
        self.gridLayout_29.addWidget(self.spinBox_NumberFBG, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_29.addWidget(self.label_20, 2, 0, 1, 3)
        self.pushButton_AddFBGPosition = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_AddFBGPosition.sizePolicy().hasHeightForWidth())
        self.pushButton_AddFBGPosition.setSizePolicy(sizePolicy)
        self.pushButton_AddFBGPosition.setObjectName("pushButton_AddFBGPosition")
        self.gridLayout_29.addWidget(self.pushButton_AddFBGPosition, 3, 3, 1, 1)
        self.lineEdit_tolerance = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_tolerance.sizePolicy().hasHeightForWidth())
        self.lineEdit_tolerance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_tolerance.setFont(font)
        self.lineEdit_tolerance.setObjectName("lineEdit_tolerance")
        self.gridLayout_29.addWidget(self.lineEdit_tolerance, 1, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_29.addWidget(self.label_25, 1, 2, 1, 1)
        self.pushButton_AddFBGOriginalWavelength = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_AddFBGOriginalWavelength.sizePolicy().hasHeightForWidth())
        self.pushButton_AddFBGOriginalWavelength.setSizePolicy(sizePolicy)
        self.pushButton_AddFBGOriginalWavelength.setObjectName("pushButton_AddFBGOriginalWavelength")
        self.gridLayout_29.addWidget(self.pushButton_AddFBGOriginalWavelength, 10, 3, 1, 1)
        self.pushButton_AutoOSA = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_AutoOSA.sizePolicy().hasHeightForWidth())
        self.pushButton_AutoOSA.setSizePolicy(sizePolicy)
        self.pushButton_AutoOSA.setObjectName("pushButton_AutoOSA")
        self.gridLayout_29.addWidget(self.pushButton_AutoOSA, 9, 3, 1, 1)
        self.textEdit_FBGPosition = QtWidgets.QTextEdit(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_FBGPosition.setFont(font)
        self.textEdit_FBGPosition.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_FBGPosition.setObjectName("textEdit_FBGPosition")
        self.gridLayout_29.addWidget(self.textEdit_FBGPosition, 3, 0, 2, 3)
        self.textEdit_FBGOriginalWavelength = QtWidgets.QTextEdit(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_FBGOriginalWavelength.setFont(font)
        self.textEdit_FBGOriginalWavelength.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_FBGOriginalWavelength.setObjectName("textEdit_FBGOriginalWavelength")
        self.gridLayout_29.addWidget(self.textEdit_FBGOriginalWavelength, 9, 0, 3, 3)
        self.gridLayout_30.addLayout(self.gridLayout_29, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_7, 2, 2, 1, 2)
        self.groupBox_7.raise_()
        self.groupBox_12.raise_()
        self.groupBox_6.raise_()
        self.groupBox_9.raise_()
        self.groupBox_8.raise_()
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionCopyrigth = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("resources/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCopyrigth.setIcon(icon2)
        self.actionCopyrigth.setObjectName("actionCopyrigth")
        self.actionSoftwareDoc = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("resources/document.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap("resources/document.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("resources/document.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap("resources/document.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("resources/document.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap("resources/document.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("resources/document.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.actionSoftwareDoc.setIcon(icon3)
        self.actionSoftwareDoc.setObjectName("actionSoftwareDoc")
        self.actionExitProgram = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("resources/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionExitProgram.setIcon(icon4)
        self.actionExitProgram.setObjectName("actionExitProgram")
        self.actionPlotOSA = QtWidgets.QAction(MainWindow)
        self.actionPlotOSA.setObjectName("actionPlotOSA")
        self.actionLoadFolderOSA = QtWidgets.QAction(MainWindow)
        self.actionLoadFolderOSA.setObjectName("actionLoadFolderOSA")
        self.actionRemoveFileStressStrain = QtWidgets.QAction(MainWindow)
        self.actionRemoveFileStressStrain.setObjectName("actionRemoveFileStressStrain")
        self.actionAddFBGPosition = QtWidgets.QAction(MainWindow)
        self.actionAddFBGPosition.setObjectName("actionAddFBGPosition")
        self.actionClearFBGPosition = QtWidgets.QAction(MainWindow)
        self.actionClearFBGPosition.setObjectName("actionClearFBGPosition")
        self.actionAddFBGOriginalWavelength = QtWidgets.QAction(MainWindow)
        self.actionAddFBGOriginalWavelength.setObjectName("actionAddFBGOriginalWavelength")
        self.actionClearFBGOriginalWavelength = QtWidgets.QAction(MainWindow)
        self.actionClearFBGOriginalWavelength.setObjectName("actionClearFBGOriginalWavelength")
        self.actionToggleInputUnitsSIM = QtWidgets.QAction(MainWindow)
        self.actionToggleInputUnitsSIM.setObjectName("actionToggleInputUnitsSIM")
        self.actionToggleInputUnitsSIMM = QtWidgets.QAction(MainWindow)
        self.actionToggleInputUnitsSIMM.setObjectName("actionToggleInputUnitsSIMM")
        self.actionOsaGenerate = QtWidgets.QAction(MainWindow)
        self.actionOsaGenerate.setObjectName("actionOsaGenerate")
        self.actionSaveAsFileOSA = QtWidgets.QAction(MainWindow)
        self.actionSaveAsFileOSA.setObjectName("actionSaveAsFileOSA")
        self.actionAbouttheauthor = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resources/author.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap("resources/author.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAbouttheauthor.setIcon(icon5)
        self.actionAbouttheauthor.setObjectName("actionAbouttheauthor")
        self.actionAutoOSA = QtWidgets.QAction(MainWindow)
        self.actionAutoOSA.setObjectName("actionAutoOSA")
        self.actionToggleUniform = QtWidgets.QAction(MainWindow)
        self.actionToggleUniform.setObjectName("actionToggleUniform")
        self.actionToggleNonUniform = QtWidgets.QAction(MainWindow)
        self.actionToggleNonUniform.setObjectName("actionToggleNonUniform")
        self.actionHelpFileFormatOSA = QtWidgets.QAction(MainWindow)
        self.actionHelpFileFormatOSA.setObjectName("actionHelpFileFormatOSA")
        self.toolBar.addAction(self.actionSoftwareDoc)
        self.toolBar.addAction(self.actionCopyrigth)
        self.toolBar.addAction(self.actionAbouttheauthor)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExitProgram)

        self.retranslateUi(MainWindow)
        self.pushButton_ClearMessageBoard.clicked.connect(self.MessageBoard.clear)
        self.checkBox_AdvancedModeSelectionOSA.toggled['bool'].connect(self.lineEdit_InitialRefractiveIndex.setEnabled)
        self.checkBox_AdvancedModeSelectionOSA.toggled['bool'].connect(self.lineEdit_MeanChangeRefractiveIndex.setEnabled)
        self.checkBox_AdvancedModeSelectionOSA.toggled['bool'].connect(self.lineEdit_FringeVisibility.setEnabled)
        self.checkBox_AdvancedModeSelectionOSA.toggled['bool'].connect(self.lineEdit_DirectionalRefractiveP11.setEnabled)
        self.checkBox_AdvancedModeSelectionOSA.toggled['bool'].connect(self.lineEdit_DirectionalRefractiveP12.setEnabled)
        self.checkBox_AdvancedModeSelectionOSA.toggled['bool'].connect(self.lineEdit_YoungsModule.setEnabled)
        self.checkBox_AdvancedModeSelectionOSA.toggled['bool'].connect(self.lineEdit_PoissionsCoefficient.setEnabled)
        self.checkBox_AdvancedModeSelectionOSA.toggled['bool'].connect(self.lineEdit_ThermoOptic.setEnabled)
        self.checkBox_AdvancedModeSelectionOSA.toggled['bool'].connect(self.label_9.setEnabled)
        self.checkBox_AdvancedModeSelectionOSA.toggled['bool'].connect(self.label_10.setEnabled)
        self.checkBox_AdvancedModeSelectionOSA.toggled['bool'].connect(self.label_12.setEnabled)
        self.checkBox_AdvancedModeSelectionOSA.toggled['bool'].connect(self.label_13.setEnabled)
        self.checkBox_AdvancedModeSelectionOSA.toggled['bool'].connect(self.label_16.setEnabled)
        self.checkBox_AdvancedModeSelectionOSA.toggled['bool'].connect(self.label_17.setEnabled)
        self.checkBox_AdvancedModeSelectionOSA.toggled['bool'].connect(self.label_48.setEnabled)
        self.checkBox_AdvancedModeSelectionOSA.toggled['bool'].connect(self.label_14.setEnabled)
        self.checkBox_AdvancedModeSelectionOSA.toggled['bool'].connect(self.label_15.setEnabled)
        self.checkBox_TypeEmulateTemperature.toggled['bool'].connect(self.lineEdit_EmulateTemperature.setEnabled)
        self.checkBox_TypeEmulateTemperature.toggled['bool'].connect(self.label_49.setEnabled)
        self.checkBox_TypeEmulateTemperature.toggled['bool'].connect(self.lineEdit_HostThermalExpansion.setEnabled)
        self.radioButton_TypeUniform.clicked.connect(self.actionToggleUniform.trigger)
        self.radioButton_TypeNonUniform.clicked.connect(self.actionToggleNonUniform.trigger)
        self.radioButton_InputUnitsSIMM.clicked.connect(self.actionToggleInputUnitsSIMM.trigger)
        self.radioButton_InputUnitsSIM.clicked.connect(self.actionToggleInputUnitsSIM.trigger)
        self.pushButton_SaveasFileOSA.clicked.connect(self.actionSaveAsFileOSA.trigger)
        self.pushButton_RemoveFileStressStrain.clicked.connect(self.actionRemoveFileStressStrain.trigger)
        self.pushButton_PlotOSA.clicked.connect(self.actionPlotOSA.trigger)
        self.pushButton_OSAGenerate.clicked.connect(self.actionOsaGenerate.trigger)
        self.pushButton_LoadFolder.clicked.connect(self.actionLoadFolderOSA.trigger)
        self.pushButton_ClearFBGPosition.clicked.connect(self.actionClearFBGPosition.trigger)
        self.pushButton_ClearFBGOriginalWavelength.clicked.connect(self.actionClearFBGOriginalWavelength.trigger)
        self.pushButton_AutoOSA.clicked.connect(self.actionAutoOSA.trigger)
        self.pushButton_AddFBGPosition.clicked.connect(self.actionAddFBGPosition.trigger)
        self.pushButton_AddFBGOriginalWavelength.clicked.connect(self.actionAddFBGOriginalWavelength.trigger)
        self.checkBox_TypeStrain.toggled['bool'].connect(self.radioButton_TypeUniform.setEnabled)
        self.checkBox_TypeStrain.toggled['bool'].connect(self.radioButton_TypeNonUniform.setEnabled)
        self.checkBox_TypeTransverseStress.toggled['bool'].connect(self.checkBox_TypeTransverseStress.setChecked)
        self.pushButton_HelpFileFormatOSA.clicked.connect(self.actionHelpFileFormatOSA.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FBG-SimPlus V1.0"))
        self.label.setText(_translate("MainWindow", "Program Console:"))
        self.pushButton_ClearMessageBoard.setText(_translate("MainWindow", "Clear Message Board"))
        self.label_64.setText(_translate("MainWindow", "FBG-SimPlus V1.0 (Modified 2021)"))
        self.groupBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>dfsdf</p></body></html>"))
        self.groupBox_12.setTitle(_translate("MainWindow", "(3) Simulation Parameters"))
        self.label_24.setText(_translate("MainWindow", "Max"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p>Light Bandwidth [nm]</p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "Min"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p>Ambient Temperature [K]</p></body></html>"))
        self.lineEdit_MaxBandWidth.setText(_translate("MainWindow", "1600.00"))
        self.lineEdit_AmbientTemperature.setText(_translate("MainWindow", "293.15"))
        self.lineEdit_MinBandWidth.setText(_translate("MainWindow", "1500.00"))
        self.lineEdit_SimulationResolution.setText(_translate("MainWindow", "0.05"))
        self.label_26.setText(_translate("MainWindow", "Simulation Resolution [nm]"))
        self.checkBox_AdvancedModeSelectionOSA.setText(_translate("MainWindow", "Advanced Mode (Fiber Attributes)"))
        self.lineEdit_DirectionalRefractiveP11.setText(_translate("MainWindow", "0.121"))
        self.lineEdit_PoissionsCoefficient.setText(_translate("MainWindow", "0.17"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>p<span style=\" vertical-align:sub;\">1</span><span style=\" vertical-align:sub;\">2</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p>Young\'s Modulus [Pa]</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>p<span style=\" vertical-align:sub;\">11</span></p></body></html>"))
        self.lineEdit_FringeVisibility.setText(_translate("MainWindow", "1.0"))
        self.lineEdit_YoungsModule.setText(_translate("MainWindow", "75E9"))
        self.lineEdit_DirectionalRefractiveP12.setText(_translate("MainWindow", "0.270"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p>Pockels\' Elasto-optic Coefficients</p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>Poisson’s Coefficient</p></body></html>"))
        self.lineEdit_MeanChangeRefractiveIndex.setText(_translate("MainWindow", "4.5E-4"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Initial Effective Refractive Index (n<span style=\" vertical-align:sub;\">eff</span>)</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>Mean Induced Change in Refractive Index (av(δn<span style=\" vertical-align:sub;\">eff</span>))</p></body></html>"))
        self.lineEdit_InitialRefractiveIndex.setText(_translate("MainWindow", "1.46"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>Fringe Visibility</p></body></html>"))
        self.label_48.setText(_translate("MainWindow", "<html><head/><body><p>Thermo-optic Coefficient [K<span style=\" vertical-align:super;\">-1</span>]</p></body></html>"))
        self.lineEdit_ThermoOptic.setText(_translate("MainWindow", "8.3E-6"))
        self.groupBox_9.setTitle(_translate("MainWindow", "(2) Type of Simulation (Contribution)"))
        self.radioButton_TypeUniform.setText(_translate("MainWindow", "Uniform"))
        self.radioButton_TypeNonUniform.setText(_translate("MainWindow", "Uniform and Non-Uniform"))
        self.checkBox_TypeStrain.setText(_translate("MainWindow", "Longitudinal Strain"))
        self.checkBox_TypeTransverseStress.setText(_translate("MainWindow", "Transverse Stress [Pa]"))
        self.label_2.setText(_translate("MainWindow", "Emulation Options"))
        self.lineEdit_EmulateTemperature.setText(_translate("MainWindow", "293.15"))
        self.checkBox_TypeEmulateTemperature.setText(_translate("MainWindow", "Emulate Model Temperature [K]"))
        self.lineEdit_HostThermalExpansion.setText(_translate("MainWindow", "5E-5"))
        self.label_49.setText(_translate("MainWindow", "<html><head/><body><p>Host Thermal Expansion Coefficient [K<span style=\" vertical-align:super;\">-1</span>]</p></body></html>"))
        self.groupBox_6.setTitle(_translate("MainWindow", "(1) Select Stressed/Strained Path Files"))
        self.pushButton_LoadFolder.setText(_translate("MainWindow", "Add Files"))
        self.pushButton_RemoveFileStressStrain.setText(_translate("MainWindow", "Remove File"))
        self.label_30.setText(_translate("MainWindow", "Skip Rows:"))
        self.pushButton_HelpFileFormatOSA.setText(_translate("MainWindow", "File Format"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Path Distance Input Units (column one of data file)"))
        self.radioButton_InputUnitsSIM.setText(_translate("MainWindow", "Path Distance Input Unit [m]"))
        self.radioButton_InputUnitsSIMM.setText(_translate("MainWindow", "Path Distance Input Unit [mm]"))
        self.groupBox_8.setTitle(_translate("MainWindow", "(5) Spectrum Simulation"))
        self.checkBox_UndeformedSignal.setText(_translate("MainWindow", "Plot the undeformed FBG reflected signal"))
        self.pushButton_PlotOSA.setText(_translate("MainWindow", "Plot"))
        self.pushButton_OSAGenerate.setText(_translate("MainWindow", "Generate"))
        self.pushButton_SaveasFileOSA.setText(_translate("MainWindow", "Save as file (.txt)"))
        self.groupBox_7.setTitle(_translate("MainWindow", "(4) Virtual Fiber Bragg Grating Array Configuration"))
        self.pushButton_ClearFBGPosition.setText(_translate("MainWindow", "Clear"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>FBG length [mm]</p></body></html>"))
        self.lineEdit_FBGlength.setText(_translate("MainWindow", "10.0"))
        self.label_18.setText(_translate("MainWindow", "Number of FBG Sensors"))
        self.pushButton_ClearFBGOriginalWavelength.setText(_translate("MainWindow", "Clear"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>FBG Array Original Wavelength(s) <span style=\" font-weight:400;\">(λ</span><span style=\" font-weight:400; vertical-align:sub;\">b </span><span style=\" font-weight:400;\">[</span><span style=\" font-weight:400;\">nm], Ex: 1550.00 nm)</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p>FBG Position(s) <span style=\" font-weight:400;\">[mm] (Distance from start of path)</span></p></body></html>"))
        self.pushButton_AddFBGPosition.setText(_translate("MainWindow", "Add"))
        self.lineEdit_tolerance.setText(_translate("MainWindow", "0.01"))
        self.label_25.setText(_translate("MainWindow", "Tolerance [mm]"))
        self.pushButton_AddFBGOriginalWavelength.setText(_translate("MainWindow", "Manual"))
        self.pushButton_AutoOSA.setText(_translate("MainWindow", "Auto"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionCopyrigth.setText(_translate("MainWindow", "Copyright"))
        self.actionCopyrigth.setToolTip(_translate("MainWindow", "Software Information and Copyright"))
        self.actionSoftwareDoc.setText(_translate("MainWindow", "Software Documentation"))
        self.actionSoftwareDoc.setToolTip(_translate("MainWindow", "Software documentation"))
        self.actionExitProgram.setText(_translate("MainWindow", "Exit Program"))
        self.actionExitProgram.setToolTip(_translate("MainWindow", "Exit Program (the data is not saved)"))
        self.actionPlotOSA.setText(_translate("MainWindow", "PlotOSA"))
        self.actionLoadFolderOSA.setText(_translate("MainWindow", "LoadFolderOSA"))
        self.actionRemoveFileStressStrain.setText(_translate("MainWindow", "RemoveFileStressStrain"))
        self.actionAddFBGPosition.setText(_translate("MainWindow", "AddFBGPosition"))
        self.actionClearFBGPosition.setText(_translate("MainWindow", "ClearFBGPosition"))
        self.actionAddFBGOriginalWavelength.setText(_translate("MainWindow", "AddFBGOriginalWavelength"))
        self.actionClearFBGOriginalWavelength.setText(_translate("MainWindow", "ClearFBGOriginalWavelength"))
        self.actionToggleInputUnitsSIM.setText(_translate("MainWindow", "ToggleInputUnitsSIM"))
        self.actionToggleInputUnitsSIMM.setText(_translate("MainWindow", "ToggleInputUnitsSIMM"))
        self.actionOsaGenerate.setText(_translate("MainWindow", "OsaGenerate"))
        self.actionSaveAsFileOSA.setText(_translate("MainWindow", "SaveAsFileOSA"))
        self.actionAbouttheauthor.setText(_translate("MainWindow", "About the Authors"))
        self.actionAbouttheauthor.setToolTip(_translate("MainWindow", "Information About the Authors"))
        self.actionAutoOSA.setText(_translate("MainWindow", "AutoOSA"))
        self.actionToggleUniform.setText(_translate("MainWindow", "ToggleUniform"))
        self.actionToggleUniform.setToolTip(_translate("MainWindow", "ToggleUniform"))
        self.actionToggleNonUniform.setText(_translate("MainWindow", "ToggleNonUniform"))
        self.actionHelpFileFormatOSA.setText(_translate("MainWindow", "HelpFileFormatOSA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

